### ISSUE TITLE
how to get profile information

### ISSUE THREAD

**Issue by ShivdasBachewar** [Kotak-Neo/kotak-neo-api#39]
Why there is no function to fetch profile information.
API is incomplete without profile info function.
If its already there please make it visible, getting very hard time finding it.

**Comment by Kotak-Neo** [comment]
Please share us what all details you need apart from the ones you are getting in the login API response.

**Comment by ShivdasBachewar** [comment]
for the time being following 

`{'user_id': 'kotak-client-id', 'user_type': 'individual/res_no_nn', 'email': 'xxxx@gmail.com', 'user_name': 'FirstName middlename lastname',  'exchanges': ['BFO', 'NSE', 'CDS', 'MF', 'NFO', 'BSE', 'MCX'], 'products': ['CNC', 'NRML', 'MIS', 'BO', 'CO'], 'order_types': ['MARKET', 'LIMIT', 'SL', 'SL-M']}`

**Comment by ShivdasBachewar** [comment]
there should be separate profile api which i can hit and see my account details. we shall not rely on login api responce.
also look into following issue :
https://github.com/Kotak-Neo/kotak-neo-api/issues/73

**Comment by Kotak-Neo** [comment]
We have noted your feedback. :)

**Comment by geek-coder** [comment]
@Kotak-Neo 

Good to see that you are looking at some of these issues. I have raised #65 , if you get a chance please look at it, and start discussing. That's root cause why your api's fail intermittently.
Am available and can discuss this in detail on any day after market hours.
It will be good if you could also put your bug fix, or dev branch on github so that there is some transparency in your efforts  for fixing issues. Otherwise last checkins 2 months back, no updates on issues gives a very cold feeling.

Look forward for discussion with you.
