### ISSUE TITLE
How to Get Nifty 50 Monthly Future LTP?

### ISSUE THREAD

**Issue by KaushalPatel025** [Kotak-Neo/kotak-neo-api#72]
How can I get the nifty 50 monthly future prices (LTP) using Python API? I have tried the client.quotes method, but it is not working. Refer to the attached image.

![Screenshot_2023-10-06_17-24-39](https://github.com/Kotak-Neo/kotak-neo-api/assets/109354551/54c43c0d-df83-4877-b882-b697c4ca9f8c)
![Screenshot_2023-10-06_18-30-45](https://github.com/Kotak-Neo/kotak-neo-api/assets/109354551/9b0af82f-26e9-4f6b-84e6-f5916db7eaf0)

**Comment by geek-coder** [comment]
Yes there are  bugs in quotes API, however subscribe and live streaming works. Meanwhile you can use that if that helps.

**Comment by Kotak-Neo** [comment]
Hi @KaushalPatel025, I believe you want to get the Nifty 50 Index LTP, for that you need to pass nse_cm instead of nse_fo. Kindly refer below code snippet - 
`inst_tokens_Nifty_FnO = [{"instrument_token": "Nifty 50", "exchange_segment": "nse_cm"}]
client.quotes(instrument_tokens=inst_tokens_Nifty_FnO, quote_type="ltp", isIndex = True)`
